### ISSUE TITLE
0.7.0 contains screenshot that includes proprietary images from reCAPTCHA

### ISSUE THREAD

**Issue by pabs3** [taylordotfish/librecaptcha#12]
Version 0.7.0 contains a screenshot that includes proprietary images from reCAPTCHA. I'm not sure what the correct solution is here, maybe you could move it to a GitHub tag attachment and refer to it at that URL instead.

**Comment by pabs3** [comment]
FTR, this one blocks updating the Debian package of librecaptcha. It is however too late to get version 0.7.x into Debian bullseye anyway.

**Comment by taylordotfish** [comment]
Although I'm not personally concerned about having screenshots that include images from reCAPTCHA, I can understand the reticence to include them when packaging. However—and I'm not very familiar with Debian packaging, so please inform me—I'm not sure I understand why those images have to be removed from (the head of) the repository itself, rather than just excluding them during the packaging process.

**Comment by pabs3** [comment]
The images are proprietary and owned by Google, so you do not have a
license to redistribute them, neither does Debian and it probably also
makes the repository as a whole violate the GNU GPL license.

For Debian, we use a tarball generated from the git tag for the basis
of the Debian source package. All Debian source packages must fully
comply with the DFSG for packages in the "main" section of the archive,
including the entirety of the source tarball. The "non-free" section is
allowed to have proprietary software but we still have to be given a
license to distribute the software. The images from reCAPTCHA cannot be
distributed in either main or non-free. I can repack the tarball to
remove the screenshot and change the version number but it is far
better for the removal to happen in the upstream repository as Debian
prefers to contribute changes upstream and have no downstream changes.

https://sources.debian.org/src/librecaptcha/0.6.4-1/debian/watch

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by taylordotfish** [comment]
Your comment about the packaging process makes sense. I've replaced the screenshot with one that uses images licensed under CC-BY 2.0. GitHub may have cached the old image, but the new one should appear eventually. If you `git pull`, you can see it right away.

I don't want to open up a lengthy (and now basically moot) debate about legality, but I do believe that the use of a limited (vastly so, in this case) subset of images for the purpose of showing the appearance and functionality of the program and Google's reCAPTCHA service *could* fall under laws covering fair use in the United States. It may not be congruent with reCAPTCHA's terms of service, but I have not contractually agreed to those terms of service. But, as I alluded to earlier, I understand that this is not enough assurance for packaging in a major distribution. 

I disagree that this would constitute a GPL violation in any case. The README file is not a derived work of the software and is not licensed under (only) the GPL.

**Comment by pabs3** [comment]
Thanks and sorry to have to bring up this problem, I recognise that it
is fairly pedantic to be discussing this.

Unfortunately CC-BY 2.0 is considered non-free by Debian, 3.0 is free though.

GitHub projects, PyPI and Debian packaging are distributed worldwide,
but fair use isn't a concept that is world-wide, in Australia for
example we have a much more restricted concept called "fair dealing".
Consequently I believe that a reliance on fair use means a program
cannot be considered fully free software without modification, since
people that do not have fair use have less rights than Amaricans. 

Thanks for pointing out that the README.rst is CC0 licensed, I hadn't
noticed that, I will be sure to fix the Debian license information when
I next update the package.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by taylordotfish** [comment]
> Unfortunately CC-BY 2.0 is considered non-free by Debian, 3.0 is free though.

…That is unfortunate. Also unfortunate, though, is the fact that I don't really have time to hunt down alternatively licensed images for this purpose—I used Google's [Open Images](https://storage.googleapis.com/openimages/web/index.html) dataset to find the current images, as all of the images are labeled with the same category identifiers that reCAPTCHA uses, but as far as I know, all of the images in all versions of that dataset are licensed under CC-BY 2.0.

I'm not sure that hosting the image elsewhere and embedding it into the README would solve the problem—that use could still require abiding by CC-BY 2.0—so the best I can do for now is create a [no-cc-by-2.0](https://github.com/taylordotfish/librecaptcha/tree/no-cc-by-2.0) branch (and [corresponding tags](https://github.com/taylordotfish/librecaptcha/releases/tag/no-cc-by-2.0-0.7.3)) and try to keep it in sync with the master branch. That said, if someone wants to create a screenshot composed of differently licensed images, I won't stop them.

**Comment by pabs3** [comment]
I forgot to say that the reason I initially considered this a GPL
violation is that the screenshot itself is a derivative work of the GPL
licensed librecaptcha codebase that displays the user interface and the
proprietary images that are downloaded from the Google servers. It may
still be a GPL violation if CC-BY 2.0 is incompatible with the GPL.

Moving the image outside the repo would solve the problem for
redistributors, who would no longer be redistributing the image.

Next time I work on librecaptcha for Debian I will have a think about
how to solve this issue and try to do some work on it.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by taylordotfish** [comment]
I'm not *personally* concerned about license/copyright violations, especially with the current screenshot, because:

* I do not believe there are unique copyrightable elements (especially ones that both appear in the screenshot and for which I'm not the copyright holder) in librecaptcha's UI.
* Even if there are such elements, I believe that the use of a screenshot of librecaptcha's UI for informative and demonstrative purposes falls under fair use law in the United States, which is the jurisdiction that applies both to me and to GitHub.

To be clear, I'm not offering this as a justification for including the screenshot in Debian. I understand and accept the reasons why it would be problematic to do so, which is why I think the discussion about what is and isn't a license violation is somewhat off-topic: the real question is how to distribute the repository in a way that clearly complies with Debian's policies.

I'm not sure that moving the image outside the repository would solve the issue if it's still embedded in the README. The act of embedding that image in the README may itself require copyright permission, thus requiring the distribution of even just the README itself to abide by CC-BY 2.0.

These are the solutions I see:

* Use the [no-cc-by-2.0](https://github.com/taylordotfish/librecaptcha/tree/no-cc-by-2.0) branch.
* Create an alternatively licensed screenshot that conforms to the format and aesthetics of the current screenshot, and update the attribution document accordingly. I would accept a PR that does this.

If you come up with an additional solution that doesn't require significant effort on my part, I'm also open to hearing it.
