### ISSUE TITLE
Add option to skip

### ISSUE THREAD

**Issue by Lukas1818** [taylordotfish/librecaptcha#14]
I am not sure if this an issue of the [pull request](https://github.com/MrKrabat/plugin.video.wakanim/pull/36) for the [wakanim kodi addon](https://github.com/MrKrabat/plugin.video.wakanim) or an issue of this library. Sorry if did I open the issue at the wrong place.

Sometime you must select none item to solve the Captcha. (The website say something like: skip if their is no crosswalk.) But the gui force my to select minimum one item, or it does not continue.
![Bildschirmfoto vom 2021-03-20 14-25-45](https://user-images.githubusercontent.com/44570204/111871041-723ba080-8988-11eb-975b-17c7ad1fba64.png)
see https://github.com/MrKrabat/plugin.video.wakanim/pull/36#issuecomment-803334847

A option to skip or select none item would be nice. Otherwise such a Captcha could not be solved.

**Comment by taylordotfish** [comment]
I can't reproduce this issue in librecaptcha's official GUI. With “dynamic” challenges (left side of [the example screenshot](https://raw.githubusercontent.com/taylordotfish/librecaptcha/0.7.3/misc/screenshot.png)), I'm able to click “Verify” without selecting any images, and with “multicaptcha” challenges (right side of [the example screenshot](https://raw.githubusercontent.com/taylordotfish/librecaptcha/0.7.3/misc/screenshot.png)), I'm able to click “Skip”.

If you can get this issue to happen with the official GUI or CLI in the latest version of librecaptcha ([0.7.3](https://github.com/taylordotfish/librecaptcha/tree/0.7.3), which is the latest version [on PyPI](https://pypi.org/project/librecaptcha/)), then please reopen this issue. Otherwise, it's probably an issue with that other project.
